In [3]:
!pip install yfinance
!pip install bs4
!pip install nbformat

Requirement already satisfied: yfinance in /opt/conda/lib/python3.11/site-packages (0.2.51)
Requirement already satisfied: pandas>=1.3.0 in /opt/conda/lib/python3.11/site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /opt/conda/lib/python3.11/site-packages (from yfinance) (2.2.1)
Requirement already satisfied: requests>=2.31 in /opt/conda/lib/python3.11/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /opt/conda/lib/python3.11/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /opt/conda/lib/python3.11/site-packages (from yfinance) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/conda/lib/python3.11/site-packages (from yfinance) (4.2.1)
Requirement already satisfied: pytz>=2022.5 in /opt/conda/lib/python3.11/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /opt/conda/lib/python3.11/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /opt/conda/lib/python3.11/site-packages (from yfinance) (3.17.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/conda/lib/python3.11/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in /opt/conda/lib/python3.11/site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in /opt/conda/lib/python3.11/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.11/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2.9.0)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests>=2.31->yfinance) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests>=2.31->yfinance) (2024.12.14)
Requirement already satisfied: bs4 in /opt/conda/lib/python3.11/site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.11/site-packages (from bs4) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.11/site-packages (from beautifulsoup4->bs4) (2.5)
Requirement already satisfied: nbformat in /opt/conda/lib/python3.11/site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/conda/lib/python3.11/site-packages (from nbformat) (2.19.1)
Requirement already satisfied: jsonschema>=2.6 in /opt/conda/lib/python3.11/site-packages (from nbformat) (4.22.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/conda/lib/python3.11/site-packages (from nbformat) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in /opt/conda/lib/python3.11/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (0.18.0)
Requirement already satisfied: platformdirs>=2.5 in /opt/conda/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.2.1)

In [7]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup 
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [9]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [122]:
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = stock_data[stock_data.Date <= '2021-06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()

In [1]:
tesla=yf.Ticker("TSLA")

NameError: name 'yf' is not defined

In [2]:
import yfinance as yf

In [3]:
tesla=yf.Ticker("TSLA")

In [120]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [7]:
import pandas as pd

In [6]:
import requests
from bs4 import BeautifulSoup

In [8]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [17]:
tesla_data = tesla.history(period="max")

In [18]:
tesla_data.head(5)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [19]:
tesla_data.reset_index(inplace=True)

In [20]:
tesla_data.head(5)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [21]:
url="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"

In [22]:
data  = requests.get(url).text
print(data)

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<link rel="canonical" href="https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue" />
		<title>Tesla Revenue 2010-2022 | TSLA | MacroTrends</title>
		<meta name="description" content="Tesla annual/quarterly revenue history and growth rate from 2010 to 2022. Revenue can be defined as the amount of money a company receives from its customers in exchange for the sales of goods or services.  Revenue is the top line item on an income statement from which all costs and expenses are subtracted to arrive at net income.

				&lt;ul style='margin-top:10px;'&gt;
				&lt;li&gt;Tesla revenue for the quarter ending September 30, 2022 was &lt;strong&gt;$21.454B&lt;/strong&gt;, a &lt;strong&gt;55.95% increase&lt;/strong&gt; year-over-year.&lt;/li&gt;
				&lt;li&gt;Tesla revenue for the twelve months ending September 30, 2022 was &lt;strong&gt;$74.863B&lt;/strong&gt;, a &lt;strong&gt;59.8% increase&lt;/strong&gt; year-over-year.&lt;/li&gt;
				&lt;li&gt;Tesla annual revenue for 2021 was &lt;strong&gt;$53.823B&lt;/strong&gt;, a &lt;strong&gt;70.67% increase&lt;/strong&gt; from 2020.&lt;/li&gt;
				&lt;li&gt;Tesla annual revenue for 2020 was &lt;strong&gt;$31.536B&lt;/strong&gt;, a &lt;strong&gt;28.31% increase&lt;/strong&gt; from 2019.&lt;/li&gt;
				&lt;li&gt;Tesla annual revenue for 2019 was &lt;strong&gt;$24.578B&lt;/strong&gt;, a &lt;strong&gt;14.52% increase&lt;/strong&gt; from 2018.&lt;/li&gt;
				&lt;/ul&gt;" />
		<meta name="robots" content="" />

		<link rel="shortcut icon" href="/assets/images/icons/FAVICON/macro-trends_favicon.ico" type="image/x-icon">

		<meta name="msvalidate.01" content="1228954C688F5907894001CD8E5E624B" />
		<meta name="google-site-verification" content="6MnD_3iDtAP1ZyoGK1YMyVIVck4r5Ws80I9xD3ue4_A" />

		<!-- Load in Roboto Font -->
		<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto:400,600,700'>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> <!--for Bootstrap CDN version-->
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

		<!-- Font Awesome -->
		<link rel="stylesheet" href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> <!--for Font Awesome CDN version-->

		<!-- Jquery, Bootstrap and Menu Javascript -->
		<script src="//code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

		<!-- Modernizr for cross-browser support -->
		<script type="text/javascript" src="/assets/javascript/modernizr-2.6.2-respond-1.1.0.min.js"></script>

		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="//www.fuelcdn.com/fuelux/3.13.0/css/fuelux.min.css">

		<!-- Latest compiled and minified JavaScript -->
		<script src="//www.fuelcdn.com/fuelux/3.13.0/js/fuelux.min.js"></script>


		 <!-- Twitter Card data -->
		  <meta name="twitter:card" content="summary_large_image">
		  <meta name="twitter:site" content="@tmacrotrends">
		  <meta name="twitter:title" content="Tesla Revenue 2010-2022 | TSLA">
		  <meta name="twitter:description" content="Tesla annual/quarterly revenue history and growth rate from 2010 to 2022. Revenue can be defined as the amount of money a company receives from its customers in exchange for the sales of goods or services.  Revenue is the top line item on an income statement from which all costs and expenses are subtracted to arrive at net income.

				<ul style='margin-top:10px;'>
				<li>Tesla revenue for the quarter ending September 30, 2022 was <strong>$21.454B</strong>, a <strong>55.95% increase</strong> year-over-year.</li>
				<li>Tesla revenue for the twelve months ending September 30, 2022 was <strong>$74.863B</strong>, a <strong>59.8% increase</strong> year-over-year.</li>
				<li>Tesla annual revenue for 2021 was <strong>$53.823B</strong>, a <strong>70.67% increase</strong> from 2020.</li>
				<li>Tesla annual revenue for 2020 was <strong>$31.536B</strong>, a <strong>28.31% increase</strong> from 2019.</li>
				<li>Tesla annual revenue for 2019 was <strong>$24.578B</strong>, a <strong>14.52% increase</strong> from 2018.</li>
				</ul>">

		  <!-- Open Graph data -->
		  <meta property="og:url" content="https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue" />
		  <meta property="og:title" content="Tesla Revenue 2010-2022 | TSLA" />
		  <meta property="og:description" content="Tesla annual/quarterly revenue history and growth rate from 2010 to 2022. Revenue can be defined as the amount of money a company receives from its customers in exchange for the sales of goods or services.  Revenue is the top line item on an income statement from which all costs and expenses are subtracted to arrive at net income.

				<ul style='margin-top:10px;'>
				<li>Tesla revenue for the quarter ending September 30, 2022 was <strong>$21.454B</strong>, a <strong>55.95% increase</strong> year-over-year.</li>
				<li>Tesla revenue for the twelve months ending September 30, 2022 was <strong>$74.863B</strong>, a <strong>59.8% increase</strong> year-over-year.</li>
				<li>Tesla annual revenue for 2021 was <strong>$53.823B</strong>, a <strong>70.67% increase</strong> from 2020.</li>
				<li>Tesla annual revenue for 2020 was <strong>$31.536B</strong>, a <strong>28.31% increase</strong> from 2019.</li>
				<li>Tesla annual revenue for 2019 was <strong>$24.578B</strong>, a <strong>14.52% increase</strong> from 2018.</li>
				</ul>" />

		<!-- JQXGRID STYLES AND JAVASCRIPT -->
		<link rel="stylesheet" href="/assets/php/jqfiles/jqwidgets/styles/jqx.base.css" type="text/css" />
		<link rel="stylesheet" href="/assets/php/jqfiles/jqwidgets/styles/jqx.bootstrap.css" type="text/css" />

		<!-- LOAD THESE SCRIPTS EARLY SO THE TICKER INPUT FIELD IS STYLED INSTANTLY -->
		<script type="text/javascript" src="/assets/php/jqfiles/jqwidgets/jqxcore.js"></script>
		<script type="text/javascript" src="/assets/php/jqfiles/jqwidgets/jqxdata.js"></script>
		<script type="text/javascript" src="/assets/php/jqfiles/jqwidgets/jqxinput.js"></script>

		<!-- Styling for search box -->
		<link rel="stylesheet" type="text/css" href="/assets/php/jquery-typeahead/jquery.typeahead_pages.css">

		<!-- Search box javascript -->
		<script src="/assets/php/jquery-typeahead/jquery.typeahead.min.js"></script>


		<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
		<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

	<!-- ToolTips -->
		<script src="/assets/php/tipped-4.6.1/js/tipped/tipped.js"></script>
		<link rel="stylesheet" href="/assets/php/tipped-4.6.1/css/tipped/tipped.css">


		<!-- START IC AD INSERT -->

    <script>InvestingChannelQueue = window.InvestingChannelQueue || [];</script>

	<script async src="https://u5.investingchannel.com/static/uat.js"></script>

    <script type="text/javascript">

        //Push Run command with the API-Key, so that UAT will start processing publishers request.
        InvestingChannelQueue.push(function() {
            ic_page = InvestingChannel.UAT.Run("df17ac1e-cc7f-11e8-82a5-0abbb61c4a6a");
        });

		var tickerValue = 'TSLA';
        var oopDivTag;
		var subLeaderboardTag;
		var rightSidebarTag1;
		var rightSidebarTag2;
		var searchButtonTag;
		var partner_center_tag;
		var videoTag;
		var ic_3x7_1;
 		//var IC_D_300x250_BCC;
		//var IC_D_3x7_BCC;

        //To define new tags/out of page tags.
        InvestingChannelQueue.push(function() {

			ic_page.setKval({'t': tickerValue});

            //videoTag = ic_page.defineNativeTag("Macrotrends/fundamentalanalysis","3x6, 728x90, Fluid","IC_D_3x6",35);

            oopDivTag = ic_page.defineOutOfPageTag("Macrotrends/fundamentalanalysis","oopDivTag_1");
			oopDivTag.setKval({"adslot":"IC_OOP_1"});


			LeaderboardTag = ic_page.defineTag("Macrotrends/fundamentalanalysis","970x250,728x90,970x90,fluid", "IC_D_970x250_1");
			LeaderboardTag.setKval({"adslot":"IC_D_970x250_1"});


			subLeaderboardTag = ic_page.defineTag("Macrotrends/fundamentalanalysis","728x90","ic_728x90_1");
			subLeaderboardTag.setKval({"adslot":"IC_728x90_1"});


			rightSidebarTag1 = ic_page.defineTag("Macrotrends/fundamentalanalysis","300x250,Fluid","ic_300x250_1");
			rightSidebarTag1.setKval({"adslot":"IC_300x250_1"});


			rightSidebarTag2 = ic_page.defineTag("Macrotrends/fundamentalanalysis","300x600,300x250,160x600,300x1050,Fluid","ic_300x600_1");
			rightSidebarTag2.setKval({"adslot":"IC_300x600_1"});


			searchButtonTag = ic_page.defineTag("Macrotrends/fundamentalanalysis","88x31","ic_88x31_1");
			searchButtonTag.setKval({"pc":"pc","adslot":"IC_88x31"});

			partner_center_tag = ic_page.defineTag("macrotrends/fundamentalanalysis","728x214, 728x90","IC_728x214_1");
			partner_center_tag.setKval({"pc":"pc","adslot":"d_728x90_2"});

			ic_3x7_1 = ic_page.defineNativeTag("macrotrends/fundamentalanalysis","3x7,728x90,Fluid","IC_3x7_1", 35);

			//IC_D_300x250_BCC = ic_page.defineTag(adCategory,"300x250,Fluid","IC_D_300x250_BCC");
			//IC_D_300x250_BCC.setKval({"adslot":"IC_D_300x250_BCC"});

			//IC_D_3x7_BCC = ic_page.defineTag(adCategory,"3x7, Fluid","IC_D_3x7_BCC");
			//IC_D_3x7_BCC.setKval({"adslot":"IC_D_3x7_BCC"});


        });

        //To render tags.
			InvestingChannelQueue.push(function() {
            ic_page.renderTags();
        });

    </script>

		<!-- END IC AD INSERT -->


		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-62099500-1"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'UA-62099500-1');
		</script>

		<!-- Google tag (gtag.js) -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-3KL0LYERBH"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'G-3KL0LYERBH');
		</script>


		<!--<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

			ga('create', 'UA-62099500-1', 'auto');
			ga('send', 'pageview');




			//Send one event to GA at 30 seconds to control bounce rate
			setTimeout("ga('send','event','Engaged User','30 Second Engagement')",30000);


		  //This code sends events to ga every 30 seconds when the window is in focus
			var count = 0;
			var myInterval;

			// Active
			window.addEventListener('load', startTimer);
			window.addEventListener('focus', startTimer);

			// Inactive
			window.addEventListener('blur', stopTimer);

			function timerHandler() {
				count++;

				if(count % 60 == 0 && count <= 1800) {

					var interval = (count/60);
					interval = interval.toFixed(0);

					var action = interval + " Minute Engagement";

					ga('send','event','Engaged User',action);


				}

			}

			// Start timer
			function startTimer() {
			myInterval = window.setInterval(timerHandler, 1000);
			}

			// Stop timer
			function stopTimer() {
			window.clearInterval(myInterval);
			}



		</script>-->

<style>

#style-1::-webkit-scrollbar-track
{
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
	border-radius: 3px;
	background-color: #F5F5F5;
}

#style-1::-webkit-scrollbar
{
	width: 18px;
	background-color: #F5F5F5;
}

#style-1::-webkit-scrollbar-thumb
{
	border-radius: 3px;
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.3);
	background-color: #5B9BD5;
}

html {
	width:100%;
	position: relative;
	min-height: 100%;
}

body {

	width:100%;

	/* Margin bottom by footer height */
	  margin-bottom: 80px;
	  color: #444;
	  background-color:#fff;
	  font-family: 'Roboto', sans-serif;
	  font-size:14px;
}





.header_content_container {

	min-width: 1280px;
	padding: 0px;
}

.main_content_container {

	min-width: 1280px;
	max-width: 1280px;
	padding: 0px 30px 100px 30px;

}

.sub_main_content_container {


}



#main_content {

	padding:0px 20px 0px 0px;
	width:826px;
    float:left;

}

#right_sidebar {

  width: 300px;
  float:left;
  height:3200px;

}

#sticky_ad_left {

  position: -webkit-sticky;
  position: sticky;
  top: 30px;


}

#sticky_ad_right {

  position: -webkit-sticky;
  position: sticky;
  top: 30px;


}





.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 100px;
  margin-top: 10px;
  padding: 30px 20px 20px 20px;
  color:#fff !important;
  background-color:#444;
  text-align: center;
  font-size:16px;
}

.footer a {
  color:#fff !important;
}

.ticker_search_box {

	background-color:#F5F5F5;
	border: 1px solid #E0E0E0;
	border-bottom:none;
	padding:10px 30px 10px 10px;
	margin:0px 0px 0px 0px;
	text-align:center;

}

.related_tickers {

	width:100%;
	background-color:#F5F5F5;
	border: 1px solid #E0E0E0;
	border-top: 0px;
	padding:3px 30px 3px 10px;
	margin:0px 0px 0px 0px;
	text-align:center;

}

.statement_type_select {

	width:100%;
	height:28px;

}

.frequency_select {

	width:100%;
	height:28px;
	font-weight:600;

}


.select2 {

	text-align:left;
	font-weight:600;

	}

#jqxInput {

		width:100%;
		height:28px;

}



.header__parent_container {

	width:100%;
	height:50px;
	padding:15px 0px 10px -20px;
	margin:0px 0px 0px 0px;
	background-color:#444;

}

.header_container {

	width:100%;
	height:50px;
	padding:15px 0px 10px -20px;
	margin:0px 0px 0px 0px;
	background-color:#444;

}

.header_logo {

	padding-top:10px;
	margin-left:50px;

}

.menu_parent_container {

	width:100%;
	height:34px;
	font-size:16px;
	padding:15px 0px 10px -20px;
	margin:0px 0px 0px 0px;
	background-color:#0089de;
}

.menu_container {

	width:1280px;
	height:34px;
	font-size:16px;
	padding:11px 0px 0px -20px;
	margin: 0 auto;
	background-color:#0089de;
	z-index:1000;
}

.menu_item {

	height:34px;
	float:left;
	font-size:14px;
	font-weight:bold;
	color:#fff;
	text-align:center;
	padding:7px 16px 0px 16px;

}

.menu_item:hover
{
	background-color:#32a0e4;
	cursor: pointer;
}

.menu_item a
{
	color:#fff;
	cursor: pointer;
}

.menu_item a:hover
{
	text-decoration:none;
	cursor: pointer;
}

.leaderboard_ad {

	margin-top:20px;
	margin-bottom:20px;
	text-align:center;
	min-height:100px;

}

#filter_result_count {

	width:100%;
	text-align:center;
	font-size:24px;
	font-weight:bold;
	padding:10px 15px;
	background-color:#efefef;
	border: 1px solid #dfdfdf;
	margin:20px;

}


select {
  color: #444;
  background-color: #FFF;
  border: 1px solid #AAA;
  border-radius: 4px;
  box-sizing: border-box;
  cursor: pointer;
  display: block;
  height:40px;
  line-height: 40px;
}

.historical_data_table  {
    table-layout: fixed;
	margin:20px;
}

.historical_data_table tbody tr td {

	padding:6px;
	vertical-align: middle !important;

}


.descriptors {

	text-align:center;
	font-size:14px;
	padding:15px;

}

.td_metric_name {

	width:110px;
	padding-top:17px;

}

.metric_link {

	font-size:14px;
	font-weight:bold;

}

.help_icon {

	width:15px;
	height:18px;
	padding-bottom:3px;

}

.td_min_value {

	width:75px;
	text-align:center;
	font-size:13px;

}

.td_max_value {

	width:75px;
	text-align:center;
	font-size:13px;

}

#myCombobox .form-control {

	background-color: #99d5ff;


}

.dropdown-toggle {

	height:24px;
	padding-top:0px;
	padding-left:7px;
	width:24px;

}

.dropdown-menu-right {

	min-width:75px;
	font-size:13px;

}

.form-control {

	font-size:12px;
	padding:5px 10px;
	height:24px;


}

#myPills1 {

	margin:0px 15px 10px 0px;

}

#jqxgrid {

	border-radius:0px;

}

.jqx-widget-header {

    font-family: 'Roboto', sans-serif;
	font-size:13px;

}

.jqx-item {

    font-family: 'Roboto', sans-serif;
	font-size: 13px;

}

.jqx-widget-content {

	border-color: #E0E0E0;

}

#jqxgrid .jqx-grid-cell {

	border-color: #E0E0E0;

}

#jqxgrid .jqx-grid-cell-pinned {

	border-color: #E0E0E0;
	background-color: #F5F5F5;

}

#jqxgrid .jqx-grid-column-header {

	border-color: #E0E0E0;
	background-color: #F5F5F5;

}

.clear_zero {

	height:0px;

}



/* Styles for Popup Charts */

.tpd-size-large {

	margin:0px;
	padding: 0px;
}

.popup_window_wrapper {

	margin:15px;

}

.popup_stock_name {

	font-size:16px;
	font-weight:bold;
	margin:5px;

}

.popup_stock_attributes {

	font-size:13px;
	font-weight:bold;
	margin:5px;

}

.popup_stock_description {

	font-size:12px;
	margin:5px;

}

.jqx-input {

	font-size:14px;

}

.jqx-menu-item {

	font-size:14px;

}

.jqx-input {

	padding:5px 10px;

}

.nav-tabs {
    border: 1px solid #E0E0E0;
	background-color:#F5F5F5;
	padding: 3px 5px 0px 5px;
	margin: 0px 0px 10px 0px;
}

.nav-tabs>li>a {
	font-size:13px;
	padding:7px 11px;
	font-weight:600;
    margin-right: 0px;
    line-height: 1.42857143;
    border: 0px;
    border-radius: 0px 0px 0 0;
	background-color:#F5F5F5;

}

.nav-tabs>li>a .active {
    margin-right: 0px;
    line-height: 1.42857143;
    border: 1px solid #E0E0E0;
    border-radius: 0px 0px 0 0;
	background-color:#F5F5F5;

}

.nav-tabs>li>a:hover {
    background-color: #F5F5F5;
	text-decoration: underline;

}

.donate_buttons {

	margin-left:20px;

	}

.modal-body {

	margin:10px 40px 20px 40px;
	text-align:left;
	font-size:18px;

}

.modal-body li {

	margin-top:20px;
	font-size:14px;

}


.modal_title {


	text-align:center;
	margin-bottom:30px;

}

.modal-body th{

	margin-left:10px;
	font-size:14px;
}

.modal-body td {

	color: #337ab7;
	margin-left:10px;
	font-size:14px;
}

.modal_button {

	margin-top:50px;
	text-align:center;
	font-size:16px;

}


</style>


</head>
	<body class="fuelux">
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

<div class="header_content_container container-fluid">


<div class="header_parent_container">

<div class="header_container">

	<div class="header_logo col-xs-2">
		<a class="logo" href="https://www.macrotrends.net" title="MacroTrends Home Page"><img src="/assets/images/logo_bright1.png"/></a>
	</div>


	  <div class="col-xs-1 pull-right" style="padding-top:8px; margin-right:10px; margin-left:0px; padding-left:0px;">

		<div id="ic_88x31_1">


		</div>

	  </div>


	  <div class="col-xs-5 pull-right" style="padding-top:8px;">
       <form>
        <div class="typeahead__container">
            <div class="typeahead__field">

            <span class="typeahead__query">
                <input class="js-typeahead"
                       name="q"
                       type="search"
					   placeholder="Search over 200,000 charts..."
                       autofocus
                       autocomplete="off">
            </span>
            <span class="typeahead__button">
                <button type="submit">
                    <span class="typeahead__search-icon"></span>
                </button>
            </span>

            </div>
        </div>
    </form>

	  </div>

	  </div>



</div>

<div class="menu_parent_container">

<div class="menu_container">

	<a href="/stocks/stock-screener"><div class="menu_item">Stock Screener</div></a>

In [23]:
html_data=pd.read_html(url)

In [24]:
soup = BeautifulSoup(data, 'html.parser')

In [25]:
tesla_revenue = pd.DataFrame(columns=["Date","Revenue"])

In [28]:
soup.find_all("tbody")

[<tbody>
 <tr>
 <td style="text-align:center">2021</td>
 <td style="text-align:center">$53,823</td>
 </tr>
 <tr>
 <td style="text-align:center">2020</td>
 <td style="text-align:center">$31,536</td>
 </tr>
 <tr>
 <td style="text-align:center">2019</td>
 <td style="text-align:center">$24,578</td>
 </tr>
 <tr>
 <td style="text-align:center">2018</td>
 <td style="text-align:center">$21,461</td>
 </tr>
 <tr>
 <td style="text-align:center">2017</td>
 <td style="text-align:center">$11,759</td>
 </tr>
 <tr>
 <td style="text-align:center">2016</td>
 <td style="text-align:center">$7,000</td>
 </tr>
 <tr>
 <td style="text-align:center">2015</td>
 <td style="text-align:center">$4,046</td>
 </tr>
 <tr>
 <td style="text-align:center">2014</td>
 <td style="text-align:center">$3,198</td>
 </tr>
 <tr>
 <td style="text-align:center">2013</td>
 <td style="text-align:center">$2,013</td>
 </tr>
 <tr>
 <td style="text-align:center">2012</td>
 <td style="text-align:center">$413</td>
 </tr>
 <tr>
 <td style="text-align:center">2011</td>
 <td style="text-align:center">$204</td>
 </tr>
 <tr>
 <td style="text-align:center">2010</td>
 <td style="text-align:center">$117</td>
 </tr>
 <tr>
 <td style="text-align:center">2009</td>
 <td style="text-align:center">$112</td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <td style="text-align:center">2022-09-30</td>
 <td style="text-align:center">$21,454</td>
 </tr>
 <tr>
 <td style="text-align:center">2022-06-30</td>
 <td style="text-align:center">$16,934</td>
 </tr>
 <tr>
 <td style="text-align:center">2022-03-31</td>
 <td style="text-align:center">$18,756</td>
 </tr>
 <tr>
 <td style="text-align:center">2021-12-31</td>
 <td style="text-align:center">$17,719</td>
 </tr>
 <tr>
 <td style="text-align:center">2021-09-30</td>
 <td style="text-align:center">$13,757</td>
 </tr>
 <tr>
 <td style="text-align:center">2021-06-30</td>
 <td style="text-align:center">$11,958</td>
 </tr>
 <tr>
 <td style="text-align:center">2021-03-31</td>
 <td style="text-align:center">$10,389</td>
 </tr>
 <tr>
 <td style="text-align:center">2020-12-31</td>
 <td style="text-align:center">$10,744</td>
 </tr>
 <tr>
 <td style="text-align:center">2020-09-30</td>
 <td style="text-align:center">$8,771</td>
 </tr>
 <tr>
 <td style="text-align:center">2020-06-30</td>
 <td style="text-align:center">$6,036</td>
 </tr>
 <tr>
 <td style="text-align:center">2020-03-31</td>
 <td style="text-align:center">$5,985</td>
 </tr>
 <tr>
 <td style="text-align:center">2019-12-31</td>
 <td style="text-align:center">$7,384</td>
 </tr>
 <tr>
 <td style="text-align:center">2019-09-30</td>
 <td style="text-align:center">$6,303</td>
 </tr>
 <tr>
 <td style="text-align:center">2019-06-30</td>
 <td style="text-align:center">$6,350</td>
 </tr>
 <tr>
 <td style="text-align:center">2019-03-31</td>
 <td style="text-align:center">$4,541</td>
 </tr>
 <tr>
 <td style="text-align:center">2018-12-31</td>
 <td style="text-align:center">$7,226</td>
 </tr>
 <tr>
 <td style="text-align:center">2018-09-30</td>
 <td style="text-align:center">$6,824</td>
 </tr>
 <tr>
 <td style="text-align:center">2018-06-30</td>
 <td style="text-align:center">$4,002</td>
 </tr>
 <tr>
 <td style="text-align:center">2018-03-31</td>
 <td style="text-align:center">$3,409</td>
 </tr>
 <tr>
 <td style="text-align:center">2017-12-31</td>
 <td style="text-align:center">$3,288</td>
 </tr>
 <tr>
 <td style="text-align:center">2017-09-30</td>
 <td style="text-align:center">$2,985</td>
 </tr>
 <tr>
 <td style="text-align:center">2017-06-30</td>
 <td style="text-align:center">$2,790</td>
 </tr>
 <tr>
 <td style="text-align:center">2017-03-31</td>
 <td style="text-align:center">$2,696</td>
 </tr>
 <tr>
 <td style="text-align:center">2016-12-31</td>
 <td style="text-align:center">$2,285</td>
 </tr>
 <tr>
 <td style="text-align:center">2016-09-30</td>
 <td style="text-align:center">$2,298</td>
 </tr>
 <tr>
 <td style="text-align:center">2016-06-30</td>
 <td style="text-align:center">$1,270</td>
 </tr>
 <tr>
 <td style="text-align:center">2016-03-31</td>
 <td style="text-align:center">$1,147</td>
 </tr>
 <tr>
 <td style="text-align:center">2015-12-31</td>
 <td style="text-align:center">$1,214</td>
 </tr>
 <tr>
 <td style="text-align:center">2015-09-30</td>
 <td style="text-align:center">$937</td>
 </tr>
 <tr>
 <td style="text-align:center">2015-06-30</td>
 <td style="text-align:center">$955</td>
 </tr>
 <tr>
 <td style="text-align:center">2015-03-31</td>
 <td style="text-align:center">$940</td>
 </tr>
 <tr>
 <td style="text-align:center">2014-12-31</td>
 <td style="text-align:center">$957</td>
 </tr>
 <tr>
 <td style="text-align:center">2014-09-30</td>
 <td style="text-align:center">$852</td>
 </tr>
 <tr>
 <td style="text-align:center">2014-06-30</td>
 <td style="text-align:center">$769</td>
 </tr>
 <tr>
 <td style="text-align:center">2014-03-31</td>
 <td style="text-align:center">$621</td>
 </tr>
 <tr>
 <td style="text-align:center">2013-12-31</td>
 <td style="text-align:center">$615</td>
 </tr>
 <tr>
 <td style="text-align:center">2013-09-30</td>
 <td style="text-align:center">$431</td>
 </tr>
 <tr>
 <td style="text-align:center">2013-06-30</td>
 <td style="text-align:center">$405</td>
 </tr>
 <tr>
 <td style="text-align:center">2013-03-31</td>
 <td style="text-align:center">$562</td>
 </tr>
 <tr>
 <td style="text-align:center">2012-12-31</td>
 <td style="text-align:center">$306</td>
 </tr>
 <tr>
 <td style="text-align:center">2012-09-30</td>
 <td style="text-align:center">$50</td>
 </tr>
 <tr>
 <td style="text-align:center">2012-06-30</td>
 <td style="text-align:center">$27</td>
 </tr>
 <tr>
 <td style="text-align:center">2012-03-31</td>
 <td style="text-align:center">$30</td>
 </tr>
 <tr>
 <td style="text-align:center">2011-12-31</td>
 <td style="text-align:center">$39</td>
 </tr>
 <tr>
 <td style="text-align:center">2011-09-30</td>
 <td style="text-align:center">$58</td>
 </tr>
 <tr>
 <td style="text-align:center">2011-06-30</td>
 <td style="text-align:center">$58</td>
 </tr>
 <tr>
 <td style="text-align:center">2011-03-31</td>
 <td style="text-align:center">$49</td>
 </tr>
 <tr>
 <td style="text-align:center">2010-12-31</td>
 <td style="text-align:center">$36</td>
 </tr>
 <tr>
 <td style="text-align:center">2010-09-30</td>
 <td style="text-align:center">$31</td>
 </tr>
 <tr>
 <td style="text-align:center">2010-06-30</td>
 <td style="text-align:center">$28</td>
 </tr>
 <tr>
 <td style="text-align:center">2010-03-31</td>
 <td style="text-align:center">$21</td>
 </tr>
 <tr>
 <td style="text-align:center">2009-12-31</td>
 <td style="text-align:center"></td>
 </tr>
 <tr>
 <td style="text-align:center">2009-09-30</td>
 <td style="text-align:center">$46</td>
 </tr>
 <tr>
 <td style="text-align:center">2009-06-30</td>
 <td style="text-align:center">$27</td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <td style="text-align:center"><a href="https://www.macrotrends.net/stocks/sector/5/auto-tires-trucks">Auto/Tires/Trucks</a></td>
 <td style="text-align:center"><a href="https://www.macrotrends.net/stocks/industry/7/">Auto Manufacturers - Domestic</a></td>
 <td style="text-align:center">$549.575B</td>
 <td style="text-align:center">$53.823B</td>
 </tr>
 <tr>
 <td colspan="4" style="padding:15px;">
 <span>Tesla is the market leader in battery-powered electric car sales in the United States, with roughly 70% market share. The company's flagship Model 3 is the best-selling EV model in the United States. Tesla, which has managed to garner the reputation of a gold standard over the years, is now a far bigger entity that what it started off since its IPO in 2010, with its market cap crossing $1 trillion for the first time in October 2021.? The EV king's market capitalization is more than the combined value of legacy automakers including Toyota, Volkswagen, Daimler, General Motors and Ford.Over the years, Tesla has shifted from developing niche products for affluent buyers to making more affordable EVs for the masses. The firm's three-pronged business model approach of direct sales, servicing, and charging its EVs sets it apart from other carmakers. Tesla, which is touted as the clean energy revolutionary automaker, is much more than just a car manufacturer.</span>
 </td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/GM/general-motors/revenue">General Motors (GM)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$53.930B</td>
 <td style="text-align:center">5.56</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/F/ford-motor/revenue">Ford Motor (F)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$52.668B</td>
 <td style="text-align:center">8.09</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/HOG/harley-davidson/revenue">Harley-Davidson (HOG)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$6.762B</td>
 <td style="text-align:center">9.56</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/PII/polaris/revenue">Polaris (PII)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$6.267B</td>
 <td style="text-align:center">11.86</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/IAA/iaa/revenue">IAA (IAA)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$5.134B</td>
 <td style="text-align:center">16.40</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/FSR/fisker/revenue">Fisker (FSR)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$2.261B</td>
 <td style="text-align:center">0.00</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/LEV/lion-electric/revenue">Lion Electric (LEV)</a></td>
 <td style="text-align:center">Canada</td>
 <td style="text-align:center">$0.551B</td>
 <td style="text-align:center">0.00</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/VLTA/volta/revenue">Volta (VLTA)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$0.071B</td>
 <td style="text-align:center">0.00</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/BRDS/bird-global/revenue">Bird Global (BRDS)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$0.054B</td>
 <td style="text-align:center">0.00</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/ZEV/lightning-emotors/revenue">Lightning EMotors (ZEV)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$0.043B</td>
 <td style="text-align:center">0.00</td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <td><a>Tesla Revenue 2010-2022 | TSLA</a></td>
 <td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Tesla Revenue 2010-2022 | TSLA&lt;/a&gt;"/></td>
 </tr>
 <tr>
 <td><a>Macrotrends</a></td>
 <td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Macrotrends&lt;/a&gt;"/></td>
 </tr>
 <tr>
 <td><a>Source</a></td>
 <td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Source&lt;/a&gt;"/></td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <td><a>Tesla Revenue 2010-2022 | TSLA</a></td>
 <td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Tesla Revenue 2010-2022 | TSLA&lt;/a&gt;"/></td>
 </tr>
 <tr>
 <td><a>Macrotrends</a></td>
 <td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Macrotrends&lt;/a&gt;"/></td>
 </tr>
 <tr>
 <td><a>Source</a></td>
 <td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Source&lt;/a&gt;"/></td>
 </tr>
 </tbody>]

In [29]:
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"")

In [30]:
tesla_revenue.dropna(inplace=True)

In [31]:
tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]

In [139]:
tesla_revenue

    Date Revenue
0   2021   53823
1   2020   31536
2   2019   24578
3   2018   21461
4   2017   11759
5   2016    7000
6   2015    4046
7   2014    3198
8   2013    2013
9   2012     413
10  2011     204
11  2010     117
12  2009     112

In [140]:
for row in soup.find("tbody").find_all("tr"):
    col = row.find_all("td")
    Date = col[0].text
    Revenue = col[1].text
   
tesla_revenue = pd.concat([tesla_revenue,pd.DataFrame({"Date":[Date], "Revenue":[Revenue]})], ignore_index=True)

In [141]:
tesla_revenue

    Date Revenue
0   2021   53823
1   2020   31536
2   2019   24578
3   2018   21461
4   2017   11759
5   2016    7000
6   2015    4046
7   2014    3198
8   2013    2013
9   2012     413
10  2011     204
11  2010     117
12  2009     112
13  2005  $1,843

In [36]:
read_html_pandas_data = pd.read_html(url)

In [38]:
read_html_pandas_data = pd.read_html(str(soup))

/tmp/ipykernel_2203/1034403826.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  read_html_pandas_data = pd.read_html(str(soup))

In [39]:
tesla_dataframe = read_html_pandas_data[0]

In [40]:
tesla_dataframe.tail()

,Tesla Annual Revenue (Millions of US $),Tesla Annual Revenue (Millions of US $).1
8,2013,"$2,013"
9,2012,$413
10,2011,$204
11,2010,$117
12,2009,$112

In [41]:
tesla_revenue = read_html_pandas_data[0]

In [42]:
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"")

KeyError: 'Revenue'

In [43]:
tesla_revenue

,Tesla Annual Revenue (Millions of US $),Tesla Annual Revenue (Millions of US $).1
0,2021,"$53,823"
1,2020,"$31,536"
2,2019,"$24,578"
3,2018,"$21,461"
4,2017,"$11,759"
5,2016,"$7,000"
6,2015,"$4,046"
7,2014,"$3,198"
8,2013,"$2,013"
9,2012,$413
10,2011,$204
11,2010,$117
12,2009,$112

In [44]:
tesla_revenue.dropna(inplace=True)

In [45]:
tesla_revenue.getloc[0]

AttributeError: 'DataFrame' object has no attribute 'getloc'

In [142]:
tesla_revenue[0]

KeyError: 0

In [47]:
tesla_revenue.loc[0]

Tesla Annual Revenue (Millions of US $)         2021
Tesla Annual Revenue (Millions of US $).1    $53,823
Name: 0, dtype: object

In [49]:
tesla_revenue.rename({'Tesla Annual Revenue (Millions of US $)': 'Date'}, axis=1, inplace=True)

In [143]:
tesla_revenue

    Date Revenue
0   2021   53823
1   2020   31536
2   2019   24578
3   2018   21461
4   2017   11759
5   2016    7000
6   2015    4046
7   2014    3198
8   2013    2013
9   2012     413
10  2011     204
11  2010     117
12  2009     112
13  2005  $1,843

In [51]:
tesla_revenue.rename({'Tesla Annual Revenue (Millions of US $).1': 'Revenue'}, axis=1, inplace=True)

In [52]:
tesla_revenue

    Date  Revenue
0   2021  $53,823
1   2020  $31,536
2   2019  $24,578
3   2018  $21,461
4   2017  $11,759
5   2016   $7,000
6   2015   $4,046
7   2014   $3,198
8   2013   $2,013
9   2012     $413
10  2011     $204
11  2010     $117
12  2009     $112

In [53]:
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"")

In [54]:
tesla_revenue.dropna(inplace=True)

In [55]:
tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]

In [56]:
tesla_revenue.tail()

    Date Revenue
8   2013  $2,013
9   2012    $413
10  2011    $204
11  2010    $117
12  2009    $112

In [127]:
gme=yf.Ticker("GME")

In [58]:
gme

yfinance.Ticker object <GME>

In [128]:
gme_data = gme.history(period="max")

In [129]:
gme_data.reset_index(inplace=True)

In [130]:
gme_data.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
5760,2025-01-02 00:00:00-05:00,31.840000,32.049999,30.370001,30.660000,7979700,0.0,0.0
5761,2025-01-03 00:00:00-05:00,30.799999,32.139999,30.570000,31.650000,7461800,0.0,0.0
5762,2025-01-06 00:00:00-05:00,31.700001,33.490002,30.760000,32.820000,12609400,0.0,0.0
5763,2025-01-07 00:00:00-05:00,32.799999,34.400002,31.709999,33.369999,13360700,0.0,0.0
5764,2025-01-08 00:00:00-05:00,32.970001,33.369999,32.410000,32.959999,6320000,0.0,0.0

In [131]:
gmeurl=("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html")

In [132]:
gme_data  = requests.get(gmeurl).text

In [133]:
gme_soup = BeautifulSoup(gme_data, 'html.parser')

In [134]:
read_html_pandas_gmedata = pd.read_html(gmeurl)

In [138]:
read_html_pandas_gmedata =pd.read_html((gme_soup))

TypeError: 'NoneType' object is not callable

In [136]:
gme_revenue = read_html_pandas_gmedata[0]

In [144]:
gme_revenue.tail()

,GameStop Annual Revenue (Millions of US $),GameStop Annual Revenue (Millions of US $).1
11,2009,"$8,806"
12,2008,"$7,094"
13,2007,"$5,319"
14,2006,"$3,092"
15,2005,"$1,843"

In [95]:
gme_revenue.rename({'GameStop Annual Revenue (Millions of US $)': 'Date','GameStop Annual Revenue (Millions of US $).1': 'Revenue'}, axis=1, inplace=True)

In [112]:
gme_revenue.tail()

    Date Revenue
11  2009    8806
12  2008    7094
13  2007    5319
14  2006    3092
15  2005    1843

In [111]:
gme_revenue["Revenue"] = gme_revenue["Revenue"].str.replace('$',"")

In [104]:
gme_revenue = gme_revenue[gme_revenue['Revenue'] != ""]

In [106]:
gme_revenue.dropna(inplace=True)

In [145]:
gme_dataframe.tail()

    Date Revenue
8   2012  $2,013
9   2011    $413
10  2010    $204
11  2009    $117
12  2008    $112

In [114]:
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace(',',"")

In [146]:
tesla_revenue.tail()

    Date Revenue
9   2012     413
10  2011     204
11  2010     117
12  2009     112
13  2005  $1,843

In [147]:
make_graph(tesla_data, tesla_revenue, 'Tesla')

TypeError: '<=' not supported between instances of 'int' and 'str'

In [148]:
make_graph(gme_data, gme_revenue, 'GameStop')

AttributeError: 'str' object has no attribute 'Date'